[project]
name = "mcp-beam"
version = "0.1.0"
description = "Beam integration for MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.14",
    "beam-client>=0.2.151",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "uv>=0.6.9",
]
